apiVersion: v1 
kind: ConfigMap 
metadata:
  name: prometheus-msteams-values
type: Opaque 
data: 
  values.yaml: |-
    replicaCount: 1
    image:
      repository: quay.io/prometheusmsteams/prometheus-msteams
      tag: v1.5.1

    connectors:
      - critical:
          url: ${CRITICAL_WEBHOOK_URL}
      - warning:
          url: ${WARNING_WEBHOOK_URL}

    
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus # change this accordingly
        scrapeInterval: 30s

    extraEnvs:
      - name:  CRITICAL_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: prometheus-msteams-webhooks
            key: critical
      - name:  WARNING_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: prometheus-msteams-webhooks
            key: warning
  